#! /bin/bash
if [ "$1" != "-u" ] && [ ! -z "$1" ]; then
echo '
## mod pkgbuilds and make packages from subdirs
## work with archlinux-based environment only
## use: ./mpbsmpks or ./mpbsmpks -u
## -u means an update, i.e. build and install a different versions
## Author Andrew S. License MIT
## https://github.com/quarkscript/Simple_func_scripts.git
'
exit 1
fi

fl="export CXXFLAGS+='"
fl+=$(cat cxxflags.txt)
fl+=" '"
fl2="export CFLAGS+='"
fl2+=$(cat cxxflags.txt)
fl2+=" '"
for i in $(ls -d */ | sed -e 's/\///g')
    do
        cd $i
        pkn=$(cat PKGBUILD | grep pkgname= | sed 's/.*=//g')
        pkv=$(cat PKGBUILD | grep pkgver= | sed 's/.*=//g')
        pkr=$(cat PKGBUILD | grep pkgrel= | sed 's/.*=//g')
        ipkn=$(pacman -Qe | grep "$pkn")
        if [ "$1" == "-u" ] && [ "$ipkn" != "$pkn $pkv-$pkr" ] || [ "$1" != "-u" ] ; then
            echo "processing $pkn $pkv-$pkr"
            echo '## try to force compilation flags'
            ../adnlalwp 'PKGBUILD' 'build()' "$fl"
            ../adnlalwp 'PKGBUILD' 'build()' "$fl2"
            echo '## try to force smp making'
            ../mcolif 'PKGBUILD' ' make' ' make' " make -j$(($(grep 'model name' /proc/cpuinfo --count)+1))"
            makepkg
            cp *pkg.tar.xz ../
        else
            echo "## pkg: $pkn $pkv-$pkr is already installed"
        fi
        cd ..
done
